name: Build and Push Licensed Docker Image 

on:
   [workflow_dispatch]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Format repo slug
        id: repo_slug
        run: echo "REPO_SLUG=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
 
      - name: Pull Base Docker image
        run: docker pull ghcr.io/${{ env.REPO_SLUG }}/arm-mlops-docker-base:latest

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Create license file (stub)
        run: |
          docker run -d --name build_container  -v ${{ github.workspace }}:/home/arm_mlops_docker/workspace  ghcr.io/${{ env.REPO_SLUG }}/arm-mlops-docker-base:latest sleep infinity
          docker exec build_container /home/arm_mlops_docker/ArmCompilerforEmbedded6.20/bin/armlm activate --code ${{ secrets.ARM_UBL_LICENSE_IDENTIFIER }} --as-user arm_mlops_docker --to-file /home/arm_mlops_docker/workspace/arm_mlops_docker_license
          cp ./arm_mlops_docker_license ./docker_licensed/arm_mlops_docker_license
          cat ./docker_licensed/arm_mlops_docker_license

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./docker_licensed
          push: true
          tags: ghcr.io/${{ env.REPO_SLUG }}/arm-mlops-docker-licensed:latest
