name: Licensed Docker Image - Test

on:
  workflow_run:
    workflows: ["Licensed Docker Image - Build and Push"]
    types:
      - completed
  workflow_dispatch:

jobs:
  run_test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/matthiashertel80/avh-mlops/arm-mlops-docker-licensed:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Try to execute cbuild
        run: su -l arm_mlops_docker -c "/home/arm_mlops_docker/cmsis-toolbox-linux-amd64/bin/cbuild --version"

      - name: Run test command in Docker container
        run: su -l arm_mlops_docker -c"/home/arm_mlops_docker/ArmCompilerforEmbedded6.20/bin/armclang --version"
